credentials:
  usernames:
    eraldo:
      email: eraldo@example.com
      name: Eraldo
      password: 'hashed_password_aqui'

cookie:
  name: financeiro_cookie
  key: some_random_key
  expiry_days: 30
