crcredentials:
  usernames:
    eraldo:
      email: eraldo@example.com
      name: Eraldo
      password: '$2b$12$uON60sh.2IdIk4cka2YILuRo4kQai.pU8McK/owmmJ.QawK85GrdK'
      role: admin

cookie:
  expiry_days: 30
  key: 'minha_chave_secreta'
  name: 'financeiro_cookie'
