credentials:
  usernames:
    eraldo:
      email: eraldo@email.com
      name: Eraldo
      password: senha123
    maria:
      email: maria@email.com
      name: Maria
      password: maria456

cookie:
  expiry_days: 30
  key: assinatura_segura
  name: cookie_financeiro
