credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc  # será automaticamente criptografada
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
    - jsmith@gmail.com

