credentials:
  usernames:
    eraldo:
      email: eraldo@email.com
      name: Eraldo
      password: '$2b$12$KIXQhZz1Ykz0ZQ1xZQ1xZ.Q1xZQ1xZQ1xZQ1xZQ1xZQ1xZQ1xZQ1xZ'  # senha criptografada

cookie:
  name: nome_cookie
  key: chave_secreta_aleatoria
  expiry_days: 30

preauthorized:
  emails:
    - eraldo@email.com
